### ISSUE TITLE
Parse <real>nan</real> failed

### ISSUE THREAD

**Issue by jianggaocheng** [3breadt/dd-plist#54]
```
<dict>
	<key>DownloadPercentComplete</key>
	<real>nan</real>
	<key>IsDownloaded</key>
	<true/>
	<key>ProductKey</key>
	<string>061-21545</string>
	<key>Status</key>
	<string>Idle</string>
</dict>
```

It is a MDM request from Apple Macbook, when I tried to parse it, an exception throws.
```
java.lang.IllegalArgumentException: The given string neither represents a double, an int nor a boolean value.
	at com.dd.plist.NSNumber.<init>(NSNumber.java:138)
	at com.dd.plist.XMLPropertyListParser.parseObject(XMLPropertyListParser.java:232)
	at com.dd.plist.XMLPropertyListParser.parseObject(XMLPropertyListParser.java:215)
	at com.dd.plist.XMLPropertyListParser.parseObject(XMLPropertyListParser.java:222)
	at com.dd.plist.XMLPropertyListParser.parseObject(XMLPropertyListParser.java:215)
	at com.dd.plist.XMLPropertyListParser.parse(XMLPropertyListParser.java:193)
	at com.dd.plist.XMLPropertyListParser.parse(XMLPropertyListParser.java:154)
	at com.dd.plist.PropertyListParser.parse(PropertyListParser.java:240)
	at com.dd.plist.PropertyListParser.parse(PropertyListParser.java:217)
```

**Comment by 3breadt** [comment]
Hi, I have added NaN support in release 1.23, your issue should be fixed.
