### ISSUE TITLE
NSData is not converted during toJavaObject

### ISSUE THREAD

**Issue by ivanseidel** [3breadt/dd-plist#59]
While converting a NSDictionary to a Java Object, the type `NSData` is not handled in deserialisation:

```
java.lang.IllegalArgumentException: Cannot process NSData
        at com.dd.plist.NSObject.toJavaObject(NSObject.java:319)
        at com.dd.plist.NSObject.deserializeObject(NSObject.java:356)
        at com.dd.plist.NSObject.toJavaObject(NSObject.java:316)
        at com.dd.plist.NSObject.toJavaObject(NSObject.java:184)
```

It seems that the `NSObject.toJavaObject` does not handles `NSData` case. Is this intended beharvior or is this case missing?

Library Version: 1.23

**Comment by 3breadt** [comment]
Thanks for reporting this issue. It only affect the generic toJavaObject, the other overlord worked fine. I fixed the issue in commit #73db2c2. Hope that helps.
